inherit_mode:
  merge:
    - Exclude

require:
  - standard
  - standard-custom
  - standard-performance
  - rubocop-performance
  - rubocop-rails

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml
  standard-custom: config/base.yml
  standard-rails: config/base.yml


AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'db/**/*'

Layout/ArgumentAlignment:
  EnforcedStyle: with_first_argument

Layout/AccessModifierIndentation:
  Enabled: true

Layout/ArrayAlignment:
  EnforcedStyle: with_first_element

# Layout/MultiLineArrayBraceLayout
# EnforcedStyle:

Style/EmptyElse:
  EnforcedStyle: empty

Style/RedundantReturn:
  Enabled: false
