inherit_mode:
  merge:
    - Exclude

require:
  - standard
  - standard-custom
  - standard-performance
  - rubocop-performance
  - rubocop-rails

inherit_gem:
  standard: config/base.yml
  standard-performance: config/base.yml
  standard-custom: config/base.yml
  standard-rails: config/base.yml


AllCops:
  SuggestExtensions: false
  TargetRubyVersion: 3.2

Style/RedundantReturn:
  Enabled: false
